DROP TABLE IF EXISTS "LANGUAGES" CASCADE;

CREATE TABLE "LANGUAGES"
(
    id              BIGSERIAL NOT NULL,
    name            VARCHAR(50) NOT NULL,
    code            VARCHAR(10) NOT NULL,
    "createdAt"     TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE "LANGUAGES" ADD CONSTRAINT "PK_LANGUAGES" PRIMARY KEY (id);