DROP TABLE IF EXISTS "USERS" CASCADE;

CREATE TABLE "USERS"
(
    id bigserial NOT NULL,
    "firstName" VARCHAR(100),
    "lastName" VARCHAR(100),
    gender CHAR(1),
    "birthDate" TIMESTAMP WITH TIME ZONE,
    "isActive" BOOLEAN NOT NULL,
    "languageId" BIGINT,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (id);

ALTER TABLE "USERS" ADD CONSTRAINT "FK_USERS_LANGUAGES"
    FOREIGN KEY ("languageId") REFERENCES "LANGUAGES" (id) ON DELETE NO ACTION ON UPDATE NO ACTION;