DROP TABLE IF EXISTS LOGINS CASCADE;

CREATE TABLE LOGINS
(
    id bigserial NOT NULL,
    login VARCHAR(100),
    password VARCHAR(255),
    email VARCHAR(255),
    "userId" BIGINT,
    "canLogin" BOOLEAN NOT NULL,
    "isAdmin" BOOLEAN NOT NULL DEFAULT FALSE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
);

ALTER TABLE "LOGINS" ADD CONSTRAINT "PK_LOGINS" PRIMARY KEY (id);

ALTER TABLE "LOGINS" ADD CONSTRAINT "FK_LOGINS_USERS"
    FOREIGN KEY ("userId") REFERENCES "USERS" (id) ON DELETE NO ACTION ON UPDATE NO ACTION;