DROP TABLE IF EXISTS "AUTHORS" CASCADE;

CREATE TABLE "AUTHORS"
(
    "id"            BIGSERIAL NOT NULL,
    "firstName"     VARCHAR(100) NOT NULL,
    "lastName"      VARCHAR(100) NOT NULL,
    "createdAt"     TIMESTAMP WITH TIME ZONE
);

ALTER TABLE "AUTHORS" ADD CONSTRAINT "PK_AUTHORS" PRIMARY KEY (id);